config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "dashboard#search_locations"
  get "/search_locations", to: "dashboard#search_locations"
  get "/view_weather", to: "dashboard#view_weather", as: "view_weather"
  get "/locations/favorite_locations", to: "locations#favorite_locations", as: "favorite_locations"
  post "/locations/add_to_favorites", to: "locations#add_to_favorites", as: "add_to_favorites"
  delete "/locations/remove_from_favorites/:location_id", to: "locations#remove_from_favorites",
                                                          as: "remove_from_favorites"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :name, uniqueness: { scope: :user_id }
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :name, uniqueness: { scope: %i[user_id country_code], message: 'already exists in favorites' }
  validates :country_code, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :locations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def view_weather
    @weather_data = GetWeatherData.call(location_name: params[:location], country_code: params[:country_code])

    respond_to do |format|
      format.html
      format.json do
        render json: { weather_data: @weather_data }, status: :ok
      end
    end
  rescue StandardError => e
    puts "Error: #{e}"
    flash[:warning] = 'Unable to fetch weather data'

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json do
        render json: { error: 'Unable to fetch weather data' }, status: :internal_server_error
      end
    end
  end

  def search_locations
    @locations = params[:search_query].present? ? SearchLocations.call(params[:search_query]) : []

    if @locations.any?
      respond_to do |format|
        format.html
        format.json { render json: { locations: @locations } }
      end
    else
      respond_to do |format|
        format.html do
          flash.now[:warning] = 'Location not found' if params[:search_query].present?
          render 'search_locations'
        end
        format.json { render json: { error: 'Location not found' }, status: :not_found }
      end
    end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def add_to_favorites
    location = current_user.locations.build(name: params[:location][:name],
                                            country_code: params[:location][:country_code])
    if location.save
      respond_to do |format|
        format.html do
          flash[:notice] = 'Added to favorites successfully.'
          redirect_to favorite_locations_path
        end
        format.json { render json: { status: 'success', message: 'Added to favorites successfully' }, status: :ok }
      end
    else
      respond_to do |format|
        format.html do
          flash[:warning] = "#{location.errors.full_messages[0]}"
          redirect_to favorite_locations_path
        end
        format.json do
          render json: { status: 'error', message: "#{location.errors.full_messages[0]}" },
                 status: :unprocessable_entity
        end
      end
    end
  end

  def favorite_locations
    @locations = current_user.locations
    respond_to do |format|
      format.html
      format.json { render json: { locations: @locations } }
    end
  end

  def remove_from_favorites
    location = Location.where(id: params[:location_id], user_id: current_user.id).first
    location.destroy!

    respond_to do |format|
      format.html do
        flash[:notice] = 'Location removed from favorites successfully'
        redirect_to favorite_locations_path
      end
      format.json { render json: { message: 'Location removed from favorites successfully' }, status: :ok }
    end
  rescue StandardError => e
    puts "Error: #{e}"

    respond_to do |format|
      format.html do
        flash[:warning] = 'Failed. Please try again.'
        redirect_to favorite_locations_path
      end
      format.json { render json: { message: 'Failed. Please try again.' }, status: :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/_weather.html.erb
<div class="weather flex items-center bg-blue-500 p-4 rounded-lg mx-auto my-4 hover:bg-indigo-500">
  <%= image_tag "https://openweathermap.org/img/wn/#{weather["icon"]}.png", class: "w-20 h-20"%>
  <div class="ml-4">
    <div class="text-white font-bold text-lg capitalize"><%= weather["description"] %></div>
    <span class="text-white text-sm"><%= date_time.strftime('%b %d, %Y') %></span>
    <span class="text-white text-sm"><%= date_time.strftime("%H:%M") %></span>
  </div>
</div>

app/views/dashboard/search_locations.html.erb
<div class="container flex flex-col items-center justify-center h-screen">
  <%= form_tag('/', method: 'get') do %>
    <div class="flex items-center mb-4">
      <%= label_tag(:location, "Location:", class: "mr-2") %>
      <%= text_field_tag(:search_query, "#{params[:search_query]}", class: "border rounded py-2 px-3") %>
      <%= submit_tag('Search', class: "bg-blue-500 hover:bg-blue-700 text-white font-bold ml-4 py-2 px-4 rounded") %>
    </div>
  <% end %>
  <ul id="location-results" class="w-3/12 mt-8">
    <% @locations.each do |location| %>
      <li class="flex justify-between items-center mb-4">
        <span><%= link_to "#{location[:name]}, #{location[:country_code]}", view_weather_path(location: location[:name], country_code: location[:country_code]) %></span>
        <span><%= link_to "View Weather", view_weather_path(location: location[:name], country_code: location[:country_code]), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %></span>
      </li>
    <% end %>
  </ul>
</div>

app/views/dashboard/view_weather.html.erb
<div class="container">
  <h1 class="text-3xl font-bold mb-4">
    <%= "#{@weather_data[:location][:name]}, #{@weather_data[:location][:country_code]}" %>
  </h1>
  <div class="flex items-center mb-4">
    <% if current_user.locations.where(name: @weather_data[:location][:name], country_code: @weather_data[:location][:country_code]).present? %>
      <%= link_to "New Search", root_path, class: "bg-blue-500 text-white py-2 px-4 rounded mr-4" %>
    <% else %>
      <%= form_with(url: add_to_favorites_path(location: @weather_data[:location]),
             method: :post, class: "inline-block") do |f| %>
        <%= f.submit "Add to favorites", class: "bg-blue-500 text-white py-2 px-4 rounded mr-4" %>
      <% end %>
    <% end %>
  </div>
  <div class="current-weather">
    <h2 class="text-2xl font-bold mb-4">Current weather</h2>
    <%= render partial: 'weather', locals: { weather: @weather_data[:current_weather], date_time: Time.now } %>
  </div>
  <div class="forecast">
    <h2 class="text-2xl font-bold mb-4">5-day Weather Forecast</h2>
    <% @weather_data[:forecast_data].each do |day| %>
      <%= render partial: 'weather', locals: { weather: day['weather'][0], date_time: DateTime.parse(day['dt_txt']) } %>
    <% end %>
  </div>
</div>

app/views/dashboard/weather.html.erb
<div class="container mx-auto mt-8">
  <h1 class="text-3xl font-bold mb-4"><%= "#{@location[:name]}, #{@location[:country_code]}" %></h1>
  <div class="flex items-center mb-4">
    <%= link_to "Add to favorites", add_to_favorites_path(location: @location), method: :post, class: "bg-blue-500 text-white py-2 px-4 rounded mr-4" %>
  </div>
  <div class="current-weather">
    <h2 class="text-2xl font-bold mb-4">Current weather</h2>
    <%= render partial: 'weather', locals: {weather: @current_weather, date_time: Time.now} %>
  </div>
  <div class="forecast">
    <h2 class="text-2xl font-bold mb-4">5-day Weather Forecast</h2>
    <% @forecast_data.each do |day| %>
      <%= render partial: 'weather', locals: {weather: day["weather"][0], date_time: DateTime.parse(day["dt_txt"]) } %>
    <% end %>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == 'notice' %>
    <div class="bg-blue-100 border border-teal-400 text-teal-700 px-4 py-3 rounded relative">
      <%= message %>
    </div>
  <% else %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative">
      <%= message %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="bg-white shadow-md">
  <div class="container mx-auto px-4">
    <div class="flex justify-between items-center py-4">
      <%= link_to "WeatherWatch", root_path, class: "text-lg font-semibold" %>
      <ul class="flex space-x-4">
        <%if user_signed_in? %>
          <%= link_to "Search Locations", root_path, class: "text-gray-600 hover:text-gray-800" %>
          <%= link_to "Favorite Locations", favorite_locations_path, class: "text-gray-600 hover:text-gray-800" %>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "text-gray-600 hover:text-gray-800" %>
        <% else %>
          <%= link_to "Sign In", new_user_session_url, class: "text-gray-600 hover:text-gray-800" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherWatch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash_messages' %>
    <main class="container mx-auto mt-8 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/locations/favorite_locations.html.erb
<div class="container mx-auto px-28 py-2">
  <h1 class="text-3xl font-bold mb-8">Favorite Locations</h1>
  <% if @locations.count > 0 %>
    <ul class="list-disc pl-4">
      <% @locations.each do |location| %>
        <li class="flex justify-between items-center mb-4">
          <span>
            <%= link_to "#{location.name}, #{location.country_code}", view_weather_path(location: location.name, country_code: location.country_code), class: "text-blue-500 hover:underline" %>
          </span>
          <span>
            <%= form_with(url: remove_from_favorites_path(location_id: location.id), method: :delete) do |f| %>
              <%= f.submit "Remove from favorites", class: "bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600" %>
            <% end %>
          </span>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p class="text-gray-500">User has no favorite locations.</p>
  <% end %>
</div>